version: "3.9"
services:
  api:
    container_name: relectric-api
    build:
      dockerfile: Python.Dockerfile
      context: .
    ports:
      - 8000:8000

  db:
    container_name: relectric-db
    build:
      dockerfile: Mongo.Dockerfile
      context: .
    volumes:
      - relectric:/var/lib/mongodb

  systems:
    container_name: relectric-systems
    build:
      dockerfile: Dockerfile
      context: ../systems/

volumes:
  relectric:
    external: true